name: flutter_messages_clone
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android : "launcher_icon"
  ios: true
  image_path: ""



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  fonts:
    - family: Roboto
      fonts:
      - asset: fonts/Roboto-Regular.ttf

    - family: RobotoMono
      fonts:
        #- asset: fonts/RobotoMono-Medium.ttf
        - asset: fonts/RobotoMono-Regular.ttf
        #- asset: fonts/RobotoMono-Thin.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

